CRUDappform/CRUDNEW/Controllers/PelamarController.cs
using CRUDNEW.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace CRUDNEW.Controllers
{
    public class PelamarController : Controller
    {
        // GET: Pelamar
        public ActionResult Index()
        {
            List<x_pelamar> pelamarList = new List<x_pelamar>();
            using (Applicant_DBEntities db = new Applicant_DBEntities())
            {
                pelamarList = db.x_pelamar.ToList<x_pelamar>();
            }
            return View(pelamarList);
        }

        public ActionResult Create()
        {
            return View(new x_pelamar());
        }

        [HttpPost]
        public ActionResult Create(x_pelamar pelamarmodel)
        {
            using (Applicant_DBEntities db = new Applicant_DBEntities())
            {
                db.x_pelamar.Add(pelamarmodel);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            x_pelamar pelamarmodel = new x_pelamar();
            using (Applicant_DBEntities db = new Applicant_DBEntities())
            {
                pelamarmodel = db.x_pelamar.Where(x => x.id == id).FirstOrDefault();
            };
            return View(pelamarmodel);
        }

        public ActionResult Edit(int id)
        {
            x_pelamar pelamarmodel = new x_pelamar();
            using (Applicant_DBEntities db = new Applicant_DBEntities())
            {
                pelamarmodel = db.x_pelamar.Where(x => x.id == id).FirstOrDefault();
            };
            return View(pelamarmodel);
        }

        [HttpPost]
        public ActionResult Edit(x_pelamar pelamarmodel)
        {
            
            using (Applicant_DBEntities db = new Applicant_DBEntities())
            {
                db.Entry(pelamarmodel).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            };
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {

            x_pelamar pelamarmodel = new x_pelamar();
            using (Applicant_DBEntities db = new Applicant_DBEntities())
            {
                pelamarmodel = db.x_pelamar.Where(x => x.id == id).FirstOrDefault();
            };
            return View(pelamarmodel);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
           using (Applicant_DBEntities db = new Applicant_DBEntities())
            {
                x_pelamar pelamarmodel = db.x_pelamar.Where(x => x.id==id).FirstOrDefault();
                db.x_pelamar.Remove(pelamarmodel);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    

    }
}

CRUDappform/CRUDNEW/Views/Pelamar/Create.cshtml
@model CRUDNEW.Models.x_pelamar

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <style>
            .garis {
                border-bottom: 3px solid black;
                border-top: 2px solid black;
            }

            .error {
                color: red;
            }


            .nav-item {
                border: 2px solid #337ab7;
                border-bottom: none;
            }

            .nav-item-end {
                border: 2px solid #337ab7;
                border-bottom: 2px solid #337ab7;
            }

            .modal {
                overflow-y: auto;
            }
        </style>

        <div class="col-sm-6 col-sm-9" style="margin-left:330px">

            <a href="#" class="list-group-item list-group-item-action bg-light" style="font-size:x-large;text-align:center; color:darkblue"><strong>Application Form</strong></a>
            <div class="col-lg-12" style="border-left:groove;margin-left:0px;border-right:groove">

                @*<div class="form-horizontal">*@

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-lg-12" style="margin-left:330">
                        <label style="color:darkblue">Name *</label><br />
                        <span class="text-danger" id="name_error"></span>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "Enter Name", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-lg-12" style="margin-left:330">
                        <label style="color:darkblue">Mobile Phone Number *</label><br />
                        @Html.EditorFor(model => model.MobilePhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MobilePhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group row  col-lg-pull-12" style="margin-left:175px">
                    <div class="col-sm-12" style="margin-left:330">
                        <label style="color:darkblue">Alternative Phone Number</label><br />
                        @Html.EditorFor(model => model.AlternativePhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AlternativePhoneNumber, "", new { @class = "text-danger" })
                    </div>

                </div>
                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-sm-12" style="margin-left:330">
                        <label style="color:darkblue">Email *</label><br />
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-sm-12" style="margin-left:330">
                        <label style="color:darkblue">Place Of Birth  *</label><br />
                        @Html.EditorFor(model => model.PlaceOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PlaceOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-sm-12">
                        <label style="color:darkblue">Date Of Birth  *</label><br />
                        @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-sm-12">
                        <label style="color:darkblue">Last Education  *</label><br />
                        @Html.EditorFor(model => model.LastEducation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastEducation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-sm-12">
                        <label style="color:darkblue">College/University  *</label><br />
                        @Html.EditorFor(model => model.University, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.University, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-sm-12">
                        <label style="color:darkblue">Major  *</label><br />
                        @Html.EditorFor(model => model.Major, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Major, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-sm-12">
                        <label style="color:darkblue">Position Apply  *</label><br />
                        @Html.EditorFor(model => model.PositionApply, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PositionApply, "", new { @class = "text-danger" })
                    </div>
                </div>

                @using CRUDNEW.Models
                <div class="form-group row col-lg-pull-12" style="margin-left:175px">
                    <div class="col-sm-12">

                        <label style="color:darkblue ; font-style:italic">How did you come to know this vacancy ? </label><br />
                        <label style="color:darkblue">Source *</label><br />


                        @Html.DropDownList("Source", new SelectList(Enum.GetValues(typeof(sel))), "Select Source", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Source, "", new { @class = "text-danger" })

                    </div>

                </div>

                <div class="form-group col-lg-pull-12 " style="margin-left:170px">
                    <div class="col-lg-push-3 col-lg-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                        <input type="reset" value="Reset" class="btn btn-default" />
                        @Html.ActionLink("Back", "Index")
                    </div>
                </div>
            </div>
            </div>

            @*</div>*@

            @*<div class="form-group row col-lg-pull-12">
            <div class=" col-lg-12" style="margin-left:400px">
                @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
                @Html.ActionLink("Back", "Index")
            </div>
        </div>*@

            }


</body>
</html>

<

CRUDappform/CRUDNEW/Views/Pelamar/Delete.cshtml
@model CRUDNEW.Models.x_pelamar

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <style>
        .garis {
            border-bottom: 3px solid black;
            border-top: 2px solid black;
        }


        .nav-item {
            border: 2px solid #337ab7;
            border-bottom: none;
        }

        .nav-item-end {
            border: 2px solid #337ab7;
            border-bottom: 2px solid #337ab7;
        }

        .modal {
            overflow-y: auto;
        }
    </style>

    <body>
        <div class="col-lg-6" style="margin-left:330px">
            <a href="#" class="list-group-item list-group-item-action bg-light" style="font-size:large;text-align:center; color:darkblue"><strong> Are You Sure to Delete this applicant ?</strong></a>
            <div class="col-lg-12" style="border-left:groove;margin-left:0px;border-right:groove">
                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Name</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.Name, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Mobile Phone Number</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.MobilePhoneNumber, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Alternative Phone Number</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.AlternativePhoneNumber, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Email</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.Email, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Place Of Birth</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.PlaceOfBirth, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Date Of Birth</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.DateOfBirth, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Last Education</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.LastEducation, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">College/University</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.University, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Major</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.Major, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Position Apply</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.PositionApply, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group row" style="margin-left:100px">
                    <div class="col-sm-10">
                        <label style="color:darkblue">Source</label><br />
                        <div style="border-radius:initial" class="form-control">
                            @Html.DisplayFor(model => model.Source, new { @class = "form-control" })
                        </div>
                    </div>
                </div>


                <div class="form-group row col-lg-pull-12">
                    <div class="form-actions no-color col-lg-12" style="margin-left:117px">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @*@Html.ActionLink("Edit", "Edit", new { id = Model.id }) |*@
                        @Html.ActionLink("Batal", "Index")
                    </div>
                </div>
            </div>
        </div>
    </body>
   
 @*<div class="form-group">
    
        <div class="form-actions no-color col-lg-push-3 col-lg-10">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Batal", "Index")
        </div>
    
     </div>*@
}

CRUDappform/CRUDNEW/Views/Pelamar/Details.cshtml
@model CRUDNEW.Models.x_pelamar

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
   
</head>
<body>
    <div class="col-lg-6" style="margin-left:330px">
        <a href="#" class="list-group-item list-group-item-action bg-light" style="font-size:x-large;text-align:center; color:darkblue"><strong> Details Applicant</strong></a>
        <div class="col-lg-12" style="border-left:groove;margin-left:0px;border-right:groove">
            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Name</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.Name, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Mobile Phone Number</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.MobilePhoneNumber, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Alternative Phone Number</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.AlternativePhoneNumber, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Email</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.Email, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Place Of Birth</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.PlaceOfBirth, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Date Of Birth</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.DateOfBirth, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Last Education</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.LastEducation, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">College/University</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.University, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Major</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.Major, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Position Apply</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.PositionApply, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group row" style="margin-left:100px">
                <div class="col-sm-10">
                    <label style="color:darkblue">Source</label><br />
                    <div style="border-radius:initial" class="form-control">
                        @Html.DisplayFor(model => model.Source, new { @class = "form-control" })
                    </div>
                </div>
            </div>


            <div class="form-group row col-lg-pull-12">
                <div class=" col-lg-12" style="margin-left:117px">
                    @*@Html.ActionLink("Edit", "Edit", new { id = Model.id }) |*@
                    @Html.ActionLink("Back", "Index")
                </div>
            </div>
        </div>
    </div>
</body>
</html>

CRUDappform/CRUDNEW/Views/Pelamar/Index.cshtml
@model IEnumerable<CRUDNEW.Models.x_pelamar>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Create", "Pelamar", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <!DOCTYPE html>


    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>
    </head>
    <style>
        .nav-item {
            border: 2px solid #337ab7;
            border-bottom: none;
        }

        .nav-item-end {
            border: 2px solid #337ab7;
            border-bottom: 2px solid #337ab7;
        }

        .modal {
            overflow-y: auto;
            overflow-x: auto;
        }


        .holder {
            border: 1px #337ab7 solid;
            margin-top: 0;
            border-radius: 0;
            background-color: white
        }

        .navbarlist {
            background-color: white;
            color: white
        }

        ul a:hover:not(.dropdown-toggle) {
            background-color: #337ab7;
        }

        li a:hover:not(.dropdown) {
            background-color: #337ab7;
            color: white;
        }
    </style>
    <div class="col-md-6 col-sm-12" style="justify-content:center; margin-left:330px">
        <div class="panel-heading col-sm-6" style="justify-content:center; position:center">
            <h1 style="font-size:x-large; color:darkblue" class="glyphicon glyphicon-plus-sign" aria-hidden="true">
                @Html.ActionLink("Apply", "Create")
            </h1>
        </div>

        <table class="table table-striped col-sm-6" style="justify-content:center; position:center">
            <tr class="garis" style="color:darkblue">
                <th>
                    Name
                </th>
                <th>
                    Mobile Phone Number
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>

                <th>#</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MobilePhoneNumber)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.id })
                    </td>
                </tr>
            }


        </table>

    </div>
  
}